name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]




jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      variables:
        fetch-depth: '1'
      shell: bash
      run: ./build.sh --target Restore --verbosity verbose
    - name: Build with Nuke
      variables:
        fetch-depth: '1'  
      shell: bash
      run: ./build.sh --target Compile --configuration release --verbosity verbose
   
